language: node_js
node_js: stable

addons: # Travis CI建议加的，自动更新api
  apt:
    update: true

cache:
  directories: 
  - node_modules # 缓存 node_modules

install:
- npm install # 初次安装，在CI环境中，执行安装npm依赖

# before_script: 

script:
- hexo g # 执行 hexo generate，把文章编译到public中

after_success: # 执行script成功后，进入到public，把里面的代码提交到博客的gh-pages分支
- cd ./public
- git init
- git config user.name "Junedayday"
- git config user.email "junedayday@gmail.com"
- git add .
- git commit -m "Update site"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

env:
  global:
    - GH_REF: github.com/Junedayday/code_reading
    - secure: tIhHqUUP5KybH2/kr+C9WaYamwYlFRq+Q889Vqy+fc9oLp4ujJ+cihu0KZwrAAPBDzPzPlRmksO38UBrinLy2CFq3B8Hww945kBLn2L0cWi5gkDFIckMMldoC+Y94b26Uz9EUn0EPji6s84svJDTfl5sUEGMIYzxXUQFDmBCzZDFBIB24r+Mve62gtcICeKXI/av66YnsHBFyc84OUYfZu8HVDwAop8JFhQAtAPXQUPa3lwbNzqfcXH/n3VJKFsUwo1pCrW9Eaq30xQWH06LQcb06Lerhh2a0g4Bwc3LS50CQ6Ci7iSqBrtmkeIce/9p3lctLSI2DP6gk16CQ5KJYodbIpRe8Dgj8h3frhEjwJ5QI7UrIqiZhTLjznkReYomSvht/YHXq/v8F7y9GXRkBgGf6CnyTrKI17dKWw/xVeHqxmv8S95T0XOJP+uchOxRenYCQnlfZWbXh06VINgG9raFhGK7LNhYqSo29RQuTrybyiuq+QVHPRFlXA0peDuFGVDKFEYyzxcagrv2GOjE7ub4jSTNpc9hXzji9H0oEXXxIYOyBRTtemGz7aF6isuchuvtMTR755z48mpc8OlLG640kYopTiklQ1XsYGxMz799il6PeTVuEpw7/iO0Og8Iyq1oLoq8Pk5W86g4KViHWoomQxslCBhjc0Bn4hOqmiU=
